HOTKEY_HELP := "#^'"
HOTKEY_GUI := "#^g"

HOTKEY_CMD := "#^c"
HOTKEY_Powershell := "#^o"
HOTKEY_Hosts := "#^h"
HOTKEY_Environment := "#^e"
HOTKEY_ControlPanel := "#^p"
HOTKEY_Winget := "#^w"
HOTKEY_Angular := "#^a"
HOTKEY_Services := "#^s"
HOTKEY_DiskManager := "#^d"
HOTKEY_Firewall := "#^f"
HOTKEY_Registry := "#^r"
HOTKEY_DeleteFiles := "#^q"
HOTKEY_Maintenance := "#^l"
HOTKEY_Browser := "#^z"
HOTKEY_TaskManager := "#^t"
HOTKEY_SystemUpdate := "#^u"
HOTKEY_MSStore := "#^m"
HOTKEY_FreeSpace := "#^i"
HOTKEY_TimeDate := "#^n"
HOTKEY_JavaUpdate := "#^j"
HOTKEY_OpenVPN := "#^v"
HOTKEY_VPNUpdate := "#^5"
HOTKEY_Bitlocker := "#^b"

HOTKEY_AUT_SYSTEM_ACTIVE_CANCEL := "#c"
HOTKEY_AUT_SYSTEM_ACTIVE_RESTART := "#s"

HOTKEY_FILL_WITH_DEFAULT_TEXT := "^f"
HOTKEY_FILL_WITH_CLIPBOARD := "^b"